input:
  input_type: gt_jsonl
  gt_jsonl_path: ../gt_optimization/gt/card_20251218_q2i_manucheck.jsonl
  root: /srv/workspace/Kirin_AI_Workspace/TMG_II/l00931199/datasets/card_privacy/
  dataset_name: card_gt_fix

prompt:
  dir_prompts: ./prompts/gt_fix
  prompt_type: image_multi_query_match_122b
  prompt_key: prompt_image_multi_query_match

model:
  backend: openai
  api_url: http://localhost:8000/v1
  api_key: EMPTY
  model_name: qwen3.5-122b-a10b
  model_tag: qwen35_122b_a10b
  temperature: 0.0
  top_p: 1.0
  presence_penalty: 0.0
  extra_body:
    chat_template_kwargs:
      enable_thinking: false
    top_k: -1

task_processor:
  task_processor_module: ./module_task_processor/processors/gt_fix/image_multi_query_flow_processor.py
  task_processor_name: ImageMultiQueryFlowProcessor

runtime:
  max_concurrent: 8
  max_retry: 3
  do_sample: false
  rerun: false
  resume: true

output:
  output_dir: outputs/gt_fix/card_image_multi_query_122b

extra:
  query_jsonl_paths:
    - ../gt_optimization/gt/card_20251218_q2i_manucheck.jsonl
  query_batch_size: 20
