input:
  input_type: jsonl
  jsonl_path: /path/to/test_imgs_images.jsonl

prompt:
  dir_prompts: ./prompts/gt_fix
  prompt_type: image_multi_query_match_122b
  prompt_key: prompt_image_multi_query_match

model:
  backend: http
  api_url: http://localhost:9002/v1/chat/completions
  model_name: qwen3_vl_122b
  model_tag: 122b

task_processor:
  task_processor_module: ./module_task_processor/processors/gt_fix/image_multi_query_flow_processor.py
  task_processor_name: ImageMultiQueryFlowProcessor

runtime:
  max_concurrent: 8
  max_retry: 3
  do_sample: false
  rerun: false
  resume: true

output:
  output_dir: outputs/gt_fix/test_imgs_image_multi_query_122b

extra:
  query_jsonl_paths:
    - ../gt_optimization/gt/test_imgs_rename_20251209_q2i_supplement_removelowSim_0.2.jsonl
  query_batch_size: 20
