input:
  input_type: root
  root: ./module_input_loaders/examples/images
  dataset_name: example_simple
  sample_n_per_ds: 1

prompt:
  dir_prompts: ./prompts/examples/
  prompt_type: caption_flow
  prompt_key: prompt_simple_caption
  add_info: false

model:
  backend: local
  local_entry: module_task_processor.processors.examples.local_example_entry:example_local_entry
  model_name: example-local
  model_tag: example-local

task_processor:
  task_processor_module: ./module_task_processor/processors/examples/example_flow_processor.py
  task_processor_name: SimpleCaptionFlowProcessor

runtime:
  max_concurrent: 1
  rerun: true

output:
  output_dir: outputs/examples/simple_local
